version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - "3332:3336"
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  react:
    image: node
    container_name: React
    volumes:
      - ./frontend:/root/frontend
    working_dir: /root/frontend
    command: yarn start && yarn start
    ports:
      - 3002:3000
    depends_on:
      - db
      # - server
    tty: true
    stdin_open: true
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./docker/cakephp/Dockerfile
  #   container_name: CakePHP
  #   command: ./bin/cake server
  #   ports:
  #     - 8765:8765
  #   volumes:
  #     - .:/backend
  #   depends_on:
  #     - db
  #   tty: true
  #   stdin_open: true
